### ISSUE TITLE
Add classical analysis talk slides

### ISSUE THREAD

**Issue by cdeil** [gammapy/2015-MPIK-Workshop#25]
@registerrier – Can you please add your slides from Monday here?
https://github.com/gammapy/PyGamma15/tree/gh-pages/talks/analysis-classical

**Comment by registerrier** [comment]
I cannot attach it to this comment.
I tried to commit it but the git push tells me I have no access right.

**Comment by cdeil** [comment]
@registerrier - You have write permissions to the repo now.
If it doesn't work for some reason, you can also email me the slides.

**Comment by cdeil** [comment]
@registerrier - Thanks for sending the slides. I've put them here:
https://github.com/gammapy/PyGamma15/blob/gh-pages/talks/analysis-classical/2015-11-16_PyGamma15_Terrier_Classical_Analysis.pdf
