### ISSUE TITLE
Add Fermi2 slides

### ISSUE THREAD

**Issue by cdeil** [gammapy/2015-MPIK-Workshop#27]
@woodmd - Could you please add your slides from Monday as a PDF here?
https://github.com/gammapy/PyGamma15/tree/gh-pages/talks/fermi2

**Comment by cdeil** [comment]
@woodmd - Ping.

(I'd like to write up a workshop summary and send it out next week and it would be nice if all the talks / tutorials are available by then.)

**Comment by woodmd** [comment]
Done.
