### ISSUE TITLE
Gammapy tutorial

### ISSUE THREAD

**Issue by cdeil** [gammapy/2015-MPIK-Workshop#4]
I've written down a first plan for the Gammapy tutorial at the workshop:
https://github.com/gammapy/2015-MPIK-Workshop/blob/gh-pages/tutorials/gammapy/README.md

It's pretty ambitious, but I think possible if we keep at it in the coming weeks.
Roughly this needs to be done:
- [x] Simulate some HESS or CTA data.
- [x] Implement and make a tutorial for making images
- [x] Implement and make a tutorial for making and fitting spectra
- [x] Write a Python script that participants can run, that checks if everything we need is installed and working.
- [x] Finish writing the tutorial README page, add some more infos and also a rough time schedule for the 90 minutes.

@adonath @kingj90 @peger089 - Sounds like a plan? Or did you have something else in mind for the Gammapy tutorial?

**Comment by joleroi** [comment]
@cdeil I guess I will mostly contribute to the part about spectral fitting. What do you mean by "Implement and make a tutorial" ? I was going to add a getting started section to the docs and then basically walk the participant through it - maybe using an IPython notebook.

**Comment by cdeil** [comment]
@kingj90 – I meant to implement the functionality in Gammapy (already done for spectral analysis) and then make a tutorial. If possible, I'd prefer tutorials and documentation in the official gammapy docs over separate documents / notebooks (to avoid the extra work of having to re-write that or integrate it in the Gammapy docs later).

**Comment by cdeil** [comment]
@kingj90 - Thanks for all your work on this in the past week and pulling this off!
